# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from typing import Any
from typing import Optional


@dataclass
class AccuracyConf:
    _target_: str = "pytorch_lightning.metrics.classification.Accuracy"
    threshold: float = 0.5
    top_k: Optional[int] = None
    subset_accuracy: bool = False
    compute_on_step: bool = True
    dist_sync_on_step: bool = False
    process_group: Any = None
    dist_sync_fn: Any = None  # Callable


@dataclass
class PrecisionConf:
    _target_: str = "pytorch_lightning.metrics.classification.Precision"
    num_classes: Optional[int] = None
    threshold: float = 0.5
    average: str = "micro"
    multilabel: bool = False
    mdmc_average: Optional[str] = None
    ignore_index: Optional[int] = None
    top_k: Optional[int] = None
    is_multiclass: Optional[bool] = None
    compute_on_step: bool = True
    dist_sync_on_step: bool = False
    process_group: Any = None
    dist_sync_fn: Any = None  # Callable
