# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from typing import Any


@dataclass
class MinMaxScalerConf:
    _target_: str = "sklearn.preprocessing.MinMaxScaler"
    feature_range: Any = (0, 1)
    copy: Any = True
    clip: Any = False


@dataclass
class StandardScalerConf:
    _target_: str = "sklearn.preprocessing.StandardScaler"
    copy: Any = True
    with_mean: Any = True
    with_std: Any = True
